#!/usr/bin/python2.7

import sys
import os
import numpy as np
import matplotlib.pyplot as plt

lines = [] 

with open(sys.argv[1], "r") as f:
	line = f.readline()
	while line:
		num = line.strip()
		#print(num)
		line = f.readline()
		lines.append(float(num))


N = len(lines)

ind = np.arange(N)  # the x locations for the groups
width = 1.00        # the width of the bars


fig = plt.figure(figsize=(11,5),dpi=100)
ax = fig.add_subplot(111)
rects1 = ax.bar(ind, lines, width)
ax.set_autoscalex_on(False)
ax.set_xlim([0,N]) #27103 files
ax.set_ylim([0,8]) 

ax.set_ylabel('Entropy')
ax.set_xlabel('Files')
ax.set_title('Entropy values\nFILENAME: ' + sys.argv[1])

plt.show()
