#!/bin/bash

#number of files that will be analyzed
nfiles=$(find . -type f | wc -l)
pfiles=0

touch high_entropy_files.tmp

while IFS= read -r -d '' -u 9
do
    entropcalc $REPLY >> ./entropies.tmp
    val=$(tail -n 1 entropies)
    #FIND HIGH ENTROPIES
    #Piping through the basic calculator command bc returns either 1 or 0.
	#The option -l is equivalent to --mathlib; it loads the standard math library.
    #Enclosing the whole expression between double parenthesis (( )) will translate these values to respectively true or false.
	if (( $(echo "$val > 6.5" |bc -l) )) ; then
	    echo "$REPLY    with entropy $val" >> high_entropy_files.tmp
	fi
	echo "$pfiles processed out of $nfiles    $REPLY"
	((pfiles++))
done 9< <( find . -type f -print0 )

mv entropies.tmp entropies
mv high_entropy_files.tmp high_entropy_files
#sort ./entropies > ./entropies_sort
#rm ./entropies
#don't need to sort

echo -e "\n\n\n"
echo "End of entropy calculations. Drawing plot..."
echo

entroplot entropies

echo
echo "Plot drawn."
echo

echo 
echo -e "\n\n\n\n\n\n\n"
echo -e "\n\n\n\n\n\n\n"
echo 
echo "- FINISHED -"
echo "------------"
echo
echo -e "Output files: \n"
echo "- entropies: list of all calculated entropies"
echo "- high_entropy_files.txt: list of files with entropy higher than 6.5"
echo -e "\n\n\n"
