#!/usr/bin/python2.7

import sys 
import math 

if len(sys.argv) != 2: 
    print "Usage: file_entropy.py [path]filename" 
    sys.exit()

# read the whole file into a byte array
f = open(sys.argv[1], "rb") 
byteArr = map(ord, f.read()) 
f.close() 
fileSize = len(byteArr) 

# calculate the frequency of each byte value in the file 
freqList = [] 
for b in range(256): 
    ctr = 0 
    for byte in byteArr: 
        if byte == b: 
            ctr += 1 
    freqList.append(float(ctr) / fileSize) 

# Shannon entropy 
ent = 0.0 
for freq in freqList: 
    if freq > 0: 
        ent = ent + freq * math.log(freq, 2) 
ent = -ent 
print ent 

